name: Release

on:
    push:
      tags:
          - 'v*'

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.1' ]
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  docker:
      needs: build
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v3

        - name: Build the Docker image
          run: docker build . -t felixhau/palindrom-checker:${GITHUB_REF_NAME#v}

        - name: Login to Docker registry
          run: docker login -u felixhau -p ${{ secrets.DOCKER_HUB_TOKEN }}
          
        - name: Push to Docker registry
          run: docker push felixhau/palindrom-checker:${GITHUB_REF_NAME#v}

  release:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Start release
        run: echo Starting release steps
